version: '3'
services:
  app:
    image: jboss/keycloak:15.0.0
    container_name: micro-auth-app
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080
